### ISSUE TITLE
Maven jib:dockerBuild in Google Cloud Build fails

### ISSUE THREAD

**Issue by dgvigil** [GoogleContainerTools/jib#1500]
**Description of the issue**:
Attempting to build and deploy a container from within Google Cloud Build.
`jib:build` wants me to authenticate within the same project where GCB and GCR run. It feels wrong to attempt to add this so I am attempting to use `jib:dockerBuild`.
 
```yaml
  - name: 'gcr.io/cloud-builders/mvn'
    id: MVN_COMPILE
    args: ['compile','jib:dockerBuild', '-Dmaven.test.skip=true', '-Ddocker.image.prefix=gcr.io/$PROJECT_ID', '-s', '.mvn/settings.xml']

images:
  - 'gcr.io/$PROJECT_ID/my-company-project'

```
But I am getting an error that Google Cloud Build does not have a docker daemon running. I can run both the `jib:build` and `jib:dockerBuild` locally, but need the CI to work as a trigger in Google Cloud Builder.

**Steps to reproduce**: 
Simply using Google cloud build via triggers or `gcloud builds submit .`

**Environment**: 

**`jib-maven-plugin` Configuration**: 
```xml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>1.0.0</version>
            </plugin>
```

**Log output**: 
```
Step #3 - "MVN_COMPILE": [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.0:dockerBuild (default-cli) on project my-company-project: Build to Docker daemon failed, perhaps you should make sure Docker is installed and you have correct privileges to run it -> [Help 1]
```

**Comment by chanseokoh** [comment]
Hi @dgvigil,

We are aware of this particular issue.

FYI, GCB recently dropped Docker from `gcr.io/cloud-builders/mvn`. In fact, now the [image has essentially become the official `mvn` Docker Hub image](https://github.com/GoogleCloudPlatform/cloud-builders/pull/451/files#diff-247b7113e7346c541004bcdce5cebb21R2). [`jib:dockerBuild` no longer works](https://github.com/GoogleCloudPlatform/cloud-builders/pull/451#issuecomment-463280241).

In fact, `jib:build` should just work and push the built image to the GCR. There's an internal bug open on GCB to make this work. The bug is that `/builder/home/.docker/config.json`, which holds the GCR credentials, is not being copied/linked into `/root/.docker/config.json` on GCB.

That said, the current ugly workaround you can use is to link that file yourself. Something like
```yaml
steps:
- name: gcr.io/cloud-builders/mvn
  dir: /root
  entrypoint: bash
  args:
  - -c
  - # Links the Docker config to /root/.docker/config.json so that Jib picks it up.
    # Note that this is only a temporary workaround.
    # See https://github.com/GoogleContainerTools/jib/pull/1479.
    |
    mkdir .docker &&
    ln -s /builder/home/.docker/config.json .docker/config.json
  volumes:
  - name: user.home
    path: /root

- name: gcr.io/cloud-builders/mvn
    id: MVN_COMPILE
    args: ['compile','jib:dockerBuild', '-Dmaven.test.skip=true', '-Ddocker.image.prefix=gcr.io/$PROJECT_ID', '-s', '.mvn/settings.xml']
  volumes:
  - name: user.home
    path: /root
```
(I know this is not pretty. Should be unnecessary once the bug is fixed.)

**Comment by chanseokoh** [comment]
Another option is to have `docker-credential-gcr` on `$PATH` by whatever means:

```yaml
- name: gcr.io/cloud-builders/mvn
  entrypoint: bash
  args:
  - -c
  - |
    export PATH=$$PATH:. &&
    curl -fsSL https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v1.5.0/docker-credential-gcr_linux_amd64-1.5.0.tar.gz | tar zxv &&
    chmod +x docker-credential-gcr &&
    mvn -B compile jib:build -Dimage=gcr.io/$PROJECT_ID/chanseok-test
```

or

```yaml
- name: gcr.io/cloud-builders/mvn
  dir: /usr/local/bin
  entrypoint: bash
  args:
  - -c
  - |
    curl -fsSL https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v1.5.0/docker-credential-gcr_linux_amd64-1.5.0.tar.gz | tar zxv &&
    chmod +x docker-credential-gcr
  volumes:
  - name: usr.local.bin
    path: /usr/local/bin
- name: gcr.io/cloud-builders/mvn
  args: ['-B', 'compile', 'jib:build', '-Dimage=gcr.io/$PROJECT_ID/chanseok-test']
  volumes:
  - name: usr.local.bin
    path: /usr/local/bin
```
