### ISSUE TITLE
No support harbor robot account

### ISSUE THREAD

**Issue by pog2g** [GoogleContainerTools/jib#1894]
**Environment**:

- *Jib version:*
- *Build tool:* 
- *OS:*

**Description of the issue**:

**Expected behavior**:

**Steps to reproduce**:

  1. No support harbor robot account
  2. 
  3. 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @pog2g,

This is my first time I heard about a robot account of Harbor, but looking at the [doc](https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#authenticate-with-a-robot-account), it does not seem any different from an ordinary account, so I am positive Jib will work as much as it will with a non-robot account. There are multiple ways to configure auth info for Jib, but I suggest you first try `docker login <your Harbor registry>` as explained in the [doc](https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#authenticate-with-a-robot-account). Once you successfully log in, the auth info will be stored in the docker config file (`~/.docker/config.json`), and Jib will pick up the credentials to auth with Harbor.

For other possible ways to provide auth info, see this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized).

**Comment by raizoor** [comment]
Hi @pog2g ,

How use you robot authentication?

In my CI/CD process (using gitlab), for example, I do this:

```
build-tags:
  stage: build
  script:
    - mvn compile -e jib:build -Djib.to.auth.username="robot$"$CI_PROJECT_NAMESPACE -Djib.to.auth.password=$HARBOR_TOKEN -Djib.to.image=harbor.sicredi.net/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  tags:
    - Java1.11
  only:
    - tags
```
Another jib configs are on my POM (static configs).
Harbor Token is a variable configured manually on git. Other variables are resolved by git.
I don't know how you need use that.
