### ISSUE TITLE
-Djib.allowInsecureRegistries=true does not seems to work

### ISSUE THREAD

**Issue by chmouel** [GoogleContainerTools/jib#2074]
**Environment**: Docker image:  gcr.io/cloud-builders/mvn

- *Jib version:* 1.6.1

- *Build tool: Maven

- *OS:* Docker Container

**Description of the issue**:

I am trying to use the `-Djib.allowInsecureRegistries=true` option to my tool and I am getting an error of this type when using it :

```
building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I am using it while building a sample helloworld application https://github.com/che-samples/console-java-simple

**Expected behavior**:

Working

**Steps to reproduce**:

  1.  Checkout https://github.com/che-samples/console-java-simple
  2.  docker run -v it to /builder/home
  3. Run
```
    - mvn
    - compile
    - com.google.cloud.tools:jib-maven-plugin:build
    - -Duser.home=/builder/home
    - -Dimage=image-registry.openshift-image-registry.svc:5000/test/image
    - -Djib.allowInsecureRegistries=true
```
  
**Log output**: 

<details>
  <summary>Full log output</summary>
<pre>
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/com/google/cloud/tools/jib-maven-plugin/maven-metadata.xml
Progress (1): 1.5 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/cloud/tools/jib-maven-plugin/maven-metadata.xml (1.5 kB at 2.5 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/google/cloud/tools/jib-maven-plugin/1.6.1/jib-maven-plugin-1.6.1.pom
Progress (1): 2.2/3.5 kB
Progress (1): 3.5 kB    

[...]

[INFO] Containerizing application to image-registry.openshift-image-registry.svc:5000/tekton-pipelines/console-java-simple...
[INFO] Retrieving registry credentials for image-registry.openshift-image-registry.svc:5000...
[INFO] Getting base image gcr.io/distroless/java:8...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.607 s
[INFO] Finished at: 2019-10-17T14:02:14Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.6.1:build (default-cli) on project console-java-simple: Build image failed: Failed to authenticate with registry image-registry.openshift-image-registry.svc:5000/tekton-pipelines/console-java-simple because: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
</pre>
</details>

**Comment by chanseokoh** [comment]
Hi @chmouel,

Just for a quick check. Does it work when you put `<allowInsecureRegistries>true` in `pom.xml`?

Unrelated, you probably don't need to set `-Duser.home=/builder/home` (even on Cloud Build). I suggest to take it out.

**Comment by briandealwis** [comment]
Off-line @chanseokoh suggested that your image registry (image-registry.openshift-image-registry.svc:5000) likely requires authentication and we don't send passwords in the clear by default.  Please try running with `-DsendCredentialsOverHttp=true`.

**Comment by chmouel** [comment]
I have tested against and this time against a image registry from the docker `registry` image and it worked, i am not sure exactly what goes on with the openshift registry that doesn't allow to upload in there, 

I am fine to close this,

**Comment by chanseokoh** [comment]
I suspect something, and I would like to understand why it's failing with insecure OpenShift registry. It may not just be the fault of OpenShift, as currently Jib doesn't honor `allowInsecureRegistries` when talking to an auth server to get an auth token, which I suspect may well be same as `openshift-image-registry.svc:5000`. If you are willing to lend us some help in analyzing and diagnosing this issue, we should be able to identify the cause and fix it. Our goal is to make Jib work seamlessly. I heard this is on Tekton, so I'm very interested too. What do you think? At least if you run Jib with `-X`, Maven will give us a stack trace where in the code it fails to verify the server.

**Comment by chmouel** [comment]
Yes no worries, I can help with that, I have tried again ` -DsendCredentialsOverHttp=true` and I am still getting the : 

```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.7.0:build (default-cli) on project console-java-simple: Build image failed: Failed to authenticate with registry image-registry.openshift-image-registry.svc:5000/che-console-java-simple because: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

The full debug with `-X` is here https://gist.github.com/chmouel/3a887ddaa0c437552b252e57a7062dab#file-debugx-txt

This is indeed with tekton.

If you have a tekton (`kubectl create -f https://raw.githubusercontent.com/openshift/tektoncd-pipeline/release-v0.7.0/openshift/release/tektoncd-pipeline-v0.7.0.yaml`) and a openshift (https://try.openshift.com) installed  you can easily test the task with : 

https://gist.github.com/chmouel/3a887ddaa0c437552b252e57a7062dab

which would push to the internal openshfit registry

**Comment by cmoulliard** [comment]
I can reproduce also this error @chmouel

**Comment by chanseokoh** [comment]
@chmouel @cmoulliard this should work now with Jib 1.8.0.

Unrelated, but you probably won't need `-Duser.home=/builder/home` as I said before.

**Comment by cmoulliard** [comment]
I did a new test using the following parameters top of ocp3 and that fails using jib-maven 2.0.0

```
    - name: build-and-push
      image: gcr.io/cloud-builders/mvn
      command:
        - mvn
        - compile
        - com.google.cloud.tools:jib-maven-plugin:2.0.0:build
        - -Djib.from.image=registry.redhat.io/redhat-openjdk-18/openjdk18-openshift
        - -Djib.allowInsecureRegistries=true
        - -Djib.from.auth.username=my-user
        - -Djib.from.auth.password=my-pwd
        - -Dimage=$(outputs.resources.image.url)
```

Error
```
[WARNING] Cannot verify server at https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:a5a9de8e13aa6dadffd906df1356f83e29779eb94d686e6762868dea568814ca . Attempting again with no TLS verification.
  | [WARNING] Cannot verify server at https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:293c6a95884c229df98f425c3d58297a868e701fe71a3b8a7d38607d21e8f996 . Attempting again with no TLS verification.
  | [WARNING] Failed to connect to https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:293c6a95884c229df98f425c3d58297a868e701fe71a3b8a7d38607d21e8f996  over HTTPS. Attempting again with HTTP.
  | [WARNING] Failed to connect to https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:a5a9de8e13aa6dadffd906df1356f83e29779eb94d686e6762868dea568814ca  over HTTPS. Attempting again with HTTP.
  | [INFO] Using base image with digest: sha256:9dab23924157b0c588f738c97b2a1f434315175b0be4156e1877028fa44360a8
  | [WARNING] Cannot verify server at https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:3a813abe0f1d7a01673bd2cd581a263ea4c3d1a4e1a994efe5bfa685eee2efba . Attempting again with no TLS verification.
  | [WARNING] Cannot verify server at https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:305d73a95c8fece2b53a34e040df1c97eb6b7f7cc4e0a7933465f0b7325e3d72 . Attempting again with no TLS verification.
  | [WARNING] Failed to connect to https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:305d73a95c8fece2b53a34e040df1c97eb6b7f7cc4e0a7933465f0b7325e3d72  over HTTPS. Attempting again with HTTP.
  | [WARNING] Failed to connect to https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:3a813abe0f1d7a01673bd2cd581a263ea4c3d1a4e1a994efe5bfa685eee2efba  over HTTPS. Attempting again with HTTP.
  | [WARNING] Cannot verify server at https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:00f17e0b37b0515380a4aece3cb72086c0356fc780ef4526f75476bea36a2c8b . Attempting again with no TLS verification.
  | [WARNING] Failed to connect to https://docker-registry.default.svc:5000/v2/test/sb-image/blobs/sha256:00f17e0b37b0515380a4aece3cb72086c0356fc780ef4526f75476bea36a2c8b  over HTTPS. Attempting again with HTTP.
  | [INFO]
  | [INFO] ------------------------------------------------------------------------
  | [INFO] BUILD FAILURE
  | [INFO] ------------------------------------------------------------------------
  | [INFO] Total time:  05:49 min
  | [INFO] Finished at: 2020-01-29T19:22:33Z
  | [INFO] ------------------------------------------------------------------------
  | [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.0.0:build (default-cli) on project rest-http: Build image failed, perhaps you should use a registry that supports HTTPS so credentials can be sent safely, or set the 'sendCredentialsOverHttp' system property to true: Required credentials for docker-registry.default.svc:5000/test/sb-image were not sent because the connection was over HTTP -> [Help 1]
  | [ERROR]
 ```
If I add to the config too `-DsendCredentialsOverHttp=true`, then we got this error
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.0.0:build (default-cli) on project rest-http: Build image failed: Failed to authenticate with registry docker-registry.default.svc:5000/test/sb-image because: server did not return 'WWW-Authenticate: Bearer' header: Basic realm=openshift,error="access denied" -> [Help 1]
```

@chanseokoh @chmouel 

This is what I experimented too here : https://github.com/tektoncd/catalog/issues/172

**Comment by chanseokoh** [comment]
Did it work with Jib 1.8.0? (https://github.com/GoogleContainerTools/jib/issues/2074#issuecomment-554476746)

**Comment by cmoulliard** [comment]
> Did it work with Jib 1.8.0?

No as I will suffer from another error when images are pulled from quay or red hat registry
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.8.0:build (default-cli) on project rest-http: Build image failed, perhaps you should make sure you have permissions for registry.redhat.io/redhat-openjdk-18/openjdk18-openshift and set correct credentials. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-forbidden-or-denied  for help: Unauthorized for registry.redhat.io/redhat-openjdk-18/openjdk18-openshift: 403 Forbidden
--
  | [ERROR] <HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
  | [ERROR] An error occurred while processing your request.<p>
```

**Comment by chanseokoh** [comment]
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.0.0:build (default-cli) on project rest-http: 
Build image failed: Failed to authenticate with registry docker-registry.default.svc:5000/test/sb-image 
because: server did not return 'WWW-Authenticate: Bearer' header: Basic 
realm=openshift,error="access denied" -> [Help 1]
```

This is weird. This can happen in the following case:

1. The registry (`docker-registry.default.svc:5000`) initially requested and accepted bearer authentication. (That is, the registry returned `WWW-Authenticate: Bearer ...`). The registry returned a working auth token.
2. Jib uses the returned token for subsequent registry API calls. The token works for a while.
3. Sometime later, the registry returned "401 Unauthorized" when Jib tried to use the same token, most likely because the token has expired after 5 minutes.
4. Jib should now try to refresh the bearer token, but the server returned `WWW-Authenticate: Basic ...` instead of `WWW-Authenticate: Brearer ...`.

This feels like the server is not returning the right `WWW-Authenticate` header. @cmoulliard can you contact the registry developers?

And what is the server implementation (`https://docker-registry.default.svc:5000`) (Docker Distribution, Quay, OpenShift, CodeReady Containers, ...)? I'l like to set it up locally to reproduce this.

**Comment by chanseokoh** [comment]
> If I use `-Djib.allowInsecureRegistries=true`, then we got

I believe you meant `false`, not `true`. If so, the `SSLException` is expected because `docker-registry.default.svc:5000` speaks HTTP, not HTTPS.

**Comment by cmoulliard** [comment]
> And what is the server implementation

docker deployed on openshift

**Comment by cmoulliard** [comment]
> can you contact the registry developers?

What do you want to check here ?

**Comment by chanseokoh** [comment]
Can we chat on the gitter channel if you are available?

**Comment by cmoulliard** [comment]
> Can we chat on the gitter channel if you are available?

Tomorrow as it is too late today for me ;-)

**Comment by cmoulliard** [comment]
here is the config of the docker daemon deployed on ocp3

```
    - env:
        - name: REGISTRY_HTTP_ADDR
          value: ':5000'
        - name: REGISTRY_HTTP_NET
          value: tcp
        - name: REGISTRY_HTTP_SECRET
          value: HLs5zFGsmzi5tJ7PxeTGwIzWzHowL6evK7CWq0rY4H0=
        - name: REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ENFORCEQUOTA
          value: 'false'
      image: 'openshift/origin-docker-registry:v3.11.0'
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 5000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      name: registry
      ports:
        - containerPort: 5000
          protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 5000
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /registry
          name: registry-storage
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: registry-token-t8x7s
          readOnly: true
```
