### ISSUE TITLE
skaffold init sets `project:` to project name instead of module name

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2088]
@ivanporty said Jib generated something like this with 1.5.1 for a Spring Boot project.

```yaml
    jib:
      project: Cloud Code Hello World
      args:
      - -Dimage=java-hello-world
```

After #1974 (>= 1.6.0), Jib no longer generates `project:` for Spring Boot projects that is effectively a single-module project, but I think it still generates it when needed, and it seems like it can contain a module/project name with whitespace.

We should also verify the Gradle side too.
