### ISSUE TITLE
Is it possible to use jib for pushing container to github packages via github actions?

### ISSUE THREAD

**Issue by mystdeim** [GoogleContainerTools/jib#3160]

**Comment by chanseokoh** [comment]
Not sure if you're talking about Jib CLI or Jib Maven and Gradle plugins, but yeah. I did this before.

**Comment by chanseokoh** [comment]
BTW, [GitHub Container Registry supersedes the GitHub Packages Docker registry](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#key-differences-between-github-container-registry-and-the-docker-package-registry).

> The GitHub Container Registry supersedes the existing Packages Docker registry and is optimized to support some of the unique needs of containers.

**Comment by mystdeim** [comment]
I'm talking about Jib gradle plugin. So I have ci.yml inside ny project and I want to push my container to github registry during `./gradlew jib` builnding process. @chanseokoh please share how you did that

**Comment by chanseokoh** [comment]
What's the issue you're having? Don't know how to set `jib.to.image=`? Having an auth problem?

**Comment by mystdeim** [comment]
I don't know to write a config properly... I have .github/workflows/ci.yml:

```
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Gradle build
        run: ./gradlew build
      - name: Build and deploy with Jib
        run: ./gradlew jib
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
```

and inside my build.gradle.kts:

```
jib {
  container.creationTime = "USE_CURRENT_TIMESTAMP"
  from.image = "adoptopenjdk/openjdk15:alpine-jre"
}
```
