### ISSUE TITLE
Add example GitHub Actions workflows for jib-maven-plugin to documentation

### ISSUE THREAD

**Issue by cicirello** [GoogleContainerTools/jib#3240]
**Description of the issue**:
The documentation for the jib-maven-plugin can use example GitHub Actions workflows for using Jib to
push containerized Java apps to Docker Hub, GitHub Container Registry, etc from GitHub Actions.  In particular, 
to demonstrate how to properly, and securely login within an Actions workflow.  

**Additional Information**:

The [documentation of the jib-maven-plugin](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#using-maven-settings) 
indicates that Maven's `settings.xml` can be used for authentication.
It thus seems like it would be possible
to have Maven handle the login with appropriate use of 
`actions/setup-java` in a similar way to publishing artifacts
to Maven Central and GitHub Packages.

For example, the following steps deploy artifacts to Maven Central
and GitHub Packages (from one of my workflows, and based on GitHub
documentation).

```yml
    - name: Set up JDK 11 for deploy to github packages
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        server-id: github 

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -PgithubDeploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    - name: Set up JDK 11 for deploy to OSSRH
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        server-id: ossrh 
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Publish to Apache Maven Central
      run: mvn deploy -PossrhDeploy
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}		
```

In the following, I've adapted this to what I think will
work for pushing containers built with Jib to both Docker Hub
and the GitHub Container Registry.  Will this work?  Are there any
security issues with it?  Is there a better way to do it
from GitHub Actions?  I've assumed that the server id in `settings.xml`
must match the relevant registry (e.g., `ghcr.io` for GitHub, `docker.io` for
Docker Hub, etc).

```yml
    - name: Set up JDK 11 for deploy to GitHub Container Registry
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        server-id: ghcr.io

    - name: Publish to GitHub Container Registry
      run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.0.0:build -Dimage=ghcr.io/MY-GITHUB-ID/MY-APPLICATION
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    - name: Set up JDK 11 for deploy to Docker Hub
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        server-id: docker.io 
        server-username: DOCKER_USERNAME
        server-password: DOCKER_TOKEN

    - name: Publish to Docker Hub
      run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.0.0:build -Dimage=docker.io/MY-DOCKER-ID/MY-APPLICATION
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}		
```

Will something along the lines of the above handle the authentication
without introducing any security issues?  There is also the
docker/login-action that I'm assuming would also work for this purpose.
But since actions/setup-java is needed for mvn regardless, if that can handle
the authentication as well, it would streamline workflows compared to 
introducing an additional step for auth (provided there isn't a security issue).

If so, I'm willing to write up some example GitHub Actions 
workflows for the documentation.

**Comment by mpeddada1** [comment]
Hi @cicirello, thank you for taking the time to come up with an example! Although this might work, there can be several ways of setting up authentication through github actions and it tends to depend on the registry being used. The Jib team discussed this at length and given the fact that this example may not be the only way to do auth, we would have to hold back on making any recommendations, unfortunately. There still needs to be more research done to find the ideal way that's unique to each registry.

**Comment by chanseokoh** [comment]
FYI, this is unnecessary (unless you explicitly use the env vars somehow).
```yaml
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
```
