### ISSUE TITLE
expandClasspathDependencies doesn't expand dependencies in app/jib-classpath-file

### ISSUE THREAD

**Issue by aleks-m** [GoogleContainerTools/jib#3343]
**Environment**:

- *Jib version:* 3.1.2
- *Build tool:* Gradle 5.4.1
- *OS:* docker

**Description of the issue**: `app/jib-classpath-file` doesn't contain expanded paths even when expandClasspathDependencies is enabled (Java 8 source, custom entrypoint).

**Expected behavior**:
`app/jib-classpath-file` should contain expanded paths to dependencies. Or there should be any other way to preserve order of dependencies with non-standard entrypoint.

**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'java'
    id "com.google.cloud.tools.jib" version "3.1.2"
}

java.sourceCompatibility = JavaVersion.VERSION_1_8

  jib {
      from {
          image = "google/cloud-sdk:latest"
      }
      to {
          image = System.getenv("DOCKER_IMAGE_NAME") ?: "us.gcr.io/myrepofoobar/foo:${ciCommitRefSlug}"
          tags += (ciCommitTag ?: [])
      }
      container {
          format = "OCI"
          expandClasspathDependencies = true
      }
  }
```

Resulting container:
```
root@df-test-aleksm:/# cat app/jib-classpath-file
/app/resources:/app/classes:/app/libs/*
```

Expended dependency paths are being added only to a default entrypoint but I can't use it in my case - I am running resulting container on Kube with a custom command/args:

```
    spec:
      containers:
      - args:
        - -c
        - java -cp '/app/resources:/app/classes:/app/libs/*' com.foobar.Worker
          --param1=barbaz
          --param2=foo
          --param3=bar
        command:
        - /bin/bash
```
