### ISSUE TITLE
Provide documentation about how to parameterize at runtime.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#349]
# JVM Flags

`docker run -e "JAVA_TOOL_OPTIONS=<JVM flags>" <image name>`

or kubernetes:

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: <name>
    image: <image>
    env:
    - name: JAVA_TOOL_OPTIONS
      value: <JVM flags>
```

# Environment

`docker run -e "NAME=VALUE" <image name>`

or kubernetes:

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: <name>
    image: <image>
    env:
    - name: MY_NAME
      value: is q chen
    - name: ASK_QUESTION
      value: who ${MY_NAME}
```

# Arguments to main

`docker run <image name> <arg1> <arg2> <arg3>`

or kubernetes:

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: <name>
    image: <image>
    args:
    - <arg1>
    - <arg2>
    - <arg3>
```
