### ISSUE TITLE
Feature request: allow setting sticky-flag in directoryPermissions

### ISSUE THREAD

**Issue by tnaroska** [GoogleContainerTools/jib#3594]
**Environment:**

Jib version: jib.core 0.20.0
Build tool: N/A
OS: N/A

**Description of the issue**:

Jib only allows directoryPermissions and filePermissions of 3 octal digits. With this limitation it is not possible to set extended attributes like sticky-bit for directories or setuid/setgid for files.
For example, temp directories usually are created with mode 01777, this is not possible with jib.

**Expected behavior**:

Jib should allow extended file permission bits like sticky-flag in directoryPermissions and filePermissions.

**Steps to reproduce**:

Scenario is to add a build artifact into a docker image inside `/tmp` using jib:
```
layers:
    ...
      files:
        - src: work/artifacts/
          dest: /tmp
          includes:
            - "**/binary.tar.gz"
```
The directory `/tmp` exists in the base image with mode 1777. Due to https://github.com/GoogleContainerTools/jib/issues/1270 jib overwrites the pre-existing `/tmp` with default permissions 755.

Trying to workaround https://github.com/GoogleContainerTools/jib/issues/1270 by explicitly adding `/tmp` to my jib config:
```
layers:
    ...
      files:
        - src: jib-placeholder/
          dest: /tmp/
          properties:
            user:  "0"
            group: "0"
            directoryPermissions: "1777"
        - src: work/artifacts/
          dest: /tmp
          includes:
            - "**/binary.tar.gz"
```
This fails due to jib enforcing directoryPermissions to be 3 octal digits.

**Log output**: 
```
[cutycapt] [ERROR] com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.google.cloud.tools.jib.cli.buildfile.FilePropertiesSpec`, problem: octalPermissions must be a 3-digit octal number (000-777)
```

**Additional Information**:
Some code search showed _at least_ two places that would need to change:
- https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java#L156-L158
- https://github.com/GoogleContainerTools/jib/blob/master/jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/FilePermissions.java
