### ISSUE TITLE
Is it possible to cache gradle daemon to speed up ephemeral CI/CD runs?

### ISSUE THREAD

**Issue by AkselAllas** [GoogleContainerTools/jib#3643]
In a persistant VM I can get my jib build process down to 6-12 sec thanks to Gradle daemon already running.

In an ephemeral CI/CD Docker container (Github Actions) my build takes 1min29 sec due to Gradle daemon needing to start up.

Would it be possible to somehow cache this Gradle daemon process in Github actions?

**Comment by chanseokoh** [comment]
Based on what you said, I don't really think it's due to the Gradle daemon starting up. Are you caching Gradle and Maven artifacts? You can use [`actions/cache`](https://github.com/actions/cache/blob/main/examples.md#java---gradle).

**Comment by AkselAllas** [comment]
I have tried [actions/cache](https://github.com/actions/cache/blob/main/examples.md#java---gradle) and [gradle-build-action](https://github.com/gradle/gradle-build-action#caching) and [setup-java](https://github.com/actions/setup-java)

Every result is roughly 1min30sec

Example of uses:

```
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
```

```
      - name: Cache Gradle packages and Google Jib cache
        uses: actions/cache@v3
        with:
         path: |
          ~/.gradle
          ~/.cache/google-cloud-tools-java/jib
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
         restore-keys: ${{ runner.os }}-gradle
```
