### ISSUE TITLE
Quarkus Error when pushing image to a GCP Artifact Registry within CloudBuild

### ISSUE THREAD

**Issue by anthonydenecheau** [GoogleContainerTools/jib#3680]
Hi,

In Cloud build, i try  to push an image build with Jib on Artifact registry. I use embedded quarkus package to do it.
But I still have A Permission Denied.

```
Step #0 - "packageApp": [ERROR] Caused by: com.google.cloud.tools.jib.api.RegistryAuthenticationFailedException: Failed to authenticate with registry [europe-west3-docker.pkg.dev/scc-build-docker/show-service/show-service](https://www.google.com/url?q=http://europe-west3-docker.pkg.dev/scc-build-docker/show-service/show-service&sa=D&source=buganizer&usg=AOvVaw32os90qmfSB1iwhbiIwQs4) because: 403 Forbidden
Step #0 - "packageApp": [ERROR] GET [https://europe-west3-docker.pkg.dev/v2/token?service=europe-west3-docker.pkg.dev&scope=repository:scc-build-docker/show-service/show-service:pull,push](https://www.google.com/url?q=https://europe-west3-docker.pkg.dev/v2/token?service%3Deurope-west3-docker.pkg.dev%26scope%3Drepository:scc-build-docker/show-service/show-service:pull,push&sa=D&source=buganizer&usg=AOvVaw0lJA_lLAIlj7PdZLC642S0)
Step #0 - "packageApp": [ERROR] {"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource \"projects/scc-build-docker/locations/europe-west3/repositories/show-service\" (or it may not exist)"}]}
```

My Cloudbuild.yaml look like

```
steps:            
- id: packageApp
  name: docker.io/anthonydenecheau/quarkus-maven-build-native-image:1.4
  entrypoint: bash
  args:
    - '-c'
    - |

      mvn clean package -Pnative -Dnative-image.docker-build=true \
      -Dmaven.test.skip=true -Dquarkus.profile=prod \
      -Dquarkus.native.additional-build-args=--initialize-at-run-time=jdk.internal.platform.cgroupv2.CgroupV2Subsystem

  env:
  - "SHORT_SHA=$SHORT_SHA"
  - "GCP_IMAGE_NAME=$_[REGION-docker.pkg.dev/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME:$SHORT_SHA
```

Best regards
