### ISSUE TITLE
[jib-cli]: Reusable layers

### ISSUE THREAD

**Issue by tomassatka** [GoogleContainerTools/jib#3985]
Hi Team

We have started to use jib-cli and find the tool very useful. Don't know if you have any slack channel to discuss but will try to ask here. 

I am wondering if jib is or is planned to support reusable layers. The idea would be to define a security layer and then share it among multiple builds within the enterprise. Like a common security layer for example... I think it is applicable on buildpacks so wondering if you plan to also introduce such feature. 

thx
Tomas

**Comment by diegomarquezp** [comment]
Hi @tomassatka, is the common security layer your actual use case? If so, would you mind sharing more details of your project (if you can) in terms of your setup, structure, etc., (or a similar project to give details of the situation)?

**Comment by tomassatka** [comment]
Hi @diegomarquezp 

Security layer was just one example of such use case. 

So in that particular case it could be cacerts emitted by company that is included to all apps.
Another use cases could be agents that you can always add, for example opentelemetry for tracing, jprofiler.
The idea would be a collection of pluggable modules that could be centrally managed. 

I can draw some draft of how I would imagine it
```
apiVersion: jib/v1alpha1
kind: BuildFile

from: 
  image: foo/base-java:0.2.0

layers:
  entries:
    - name: tracing
      files:
        - src: ref://remote_layer@sha
          dest: "/opentelemetry"
    - name: security
      files:
        - src: ref://remote_layer@sha
          dest: "$JAVA_HOME/lib/security/cacerts"
    - name: envConf
      files: 
        - src: "env.sh"
          dest: "/env.sh"
    - name: application
      files:
        - src: "target/app.jar"
          dest: "/app/app.jar"

cmd: ["/bin/bash", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
```

Is that something that you consider for future?
