### ISSUE TITLE
write history as part of layer meta data.

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#875]
History might be necessary for some tools to work.

- [x] add history fields to manifest object
- [x] passthrough original history
- [x] write jib layer history
- [x] allow custom "created_by" field

expected format: 

```yaml
{
  "author": "Jib",
  "created": "1970-01-01T00:00:00Z", # or useCurrentTimeStamp
  "created_by": "jib" # or jib-gradle-plugin jib-maven-plugin (tool identifier)
}
```
